
#pragma kernel PatternKernel

Texture2D<float4> texL;
Texture2D<float4> texR;
float crossfader;
RWTexture2D<float4> outputTex;


[numthreads(16, 16, 1)]
void PatternKernel(uint3 id : SV_DispatchThreadID)
{
	float4 src = texL[id.xy];
	float4 dst = texR[id.xy];
	float outA = src.a + dst.a * (1 - src.a);
	float3 outRGB = (src.rgb * src.a + dst.rgb * dst.a * (1 - src.a))/outA;
	float4 result = float4(outRGB, outA);
    outputTex[id.xy] = result;
}
